#include <iostream>
#include <cstdlib>

#include "opendihu.h"

int main(int argc, char *argv[])
{
  // initialize everything, handle arguments and parse settings from input file
  DihuContext settings(argc, argv);
  
  // AUTOGENERATED CODE START
 problem(settings);
  // AUTOGENERATED CODE END
  
  // run the simulation
  problem.run();
  
  return EXIT_SUCCESS;
}
